name: Build & Release Ultra Tracker
on:
  push:
    tags:
      - v*.*.*
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [21]
        pnpm-version: [9]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      # Get Latest
      - name: Check out Git repository
        uses: actions/checkout@v4

      # Setup Tooling
      - name: Install pnpm v${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Configure pnpm
        if: matrix.os == 'windows-latest'
        run: pnpm config set virtual-store-dir-max-length 80

      - name: Install Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      # Dependencies
      - name: Install Dependencies
        run: pnpm install

      # Build
      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: pnpm build:linux

      - name: Build Mac
        if: matrix.os == 'macos-latest'
        run: pnpm build:mac

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: pnpm build:win

      # Push Files to Release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
